# =================================================================
# RAILWAY CONFIGURATION FILE
# Defines two services: one for the 24/7 Telegram Bot and one for
# the daily News Aggregator cron job.
# =================================================================

# --- Telegram Bot Web App Service (Runs 24/7) ---
[[service]]
name = "Telegram Bot"
# The folder containing the service (assuming it's the root of the repo)
path = "."
# Set the type to "web" since the bot uses polling and needs to run continuously
type = "web"

# Define the build and start commands explicitly
[service.build]
# Install dependencies from package.json
buildCommand = "npm install"
# Run the telegram bot script (using the 'start' script from package.json)
startCommand = "npm start"

# --- News Aggregator Cron Job Service (Runs Daily) ---
[[service]]
name = "News Aggregator Cron Job"
# The folder containing the service (assuming it's the root of the repo)
path = "."
# Set the type to "cron" for scheduled execution
type = "cron"

# Define the schedule for the cron job
[service.cron]
# Schedule: Run daily at 8:00 AM UTC
schedule = "0 8 * * *"

# Define the commands for the cron job
[service.build]
# Install dependencies (only needed if the web app isn't already running)
buildCommand = "npm install"
# Execute the news aggregation script
startCommand = "node main.mjs"
startCommand = "node telegram_bot.mjs"
